() {
  unset -m 'POWERLEVEL9K_*'
  typeset -g \
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(background_jobs context dir vcs prompt_char) \
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time) \
  POWERLEVEL9K_INSTANT_PROMPT=quiet \
  POWERLEVEL9K_TRANSIENT_PROMPT=never \
  POWERLEVEL9K_BACKGROUND= \
  POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE= \
  POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' ' \
  POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR= \
  POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='' \
  POWERLEVEL9K_PROMPT_ADD_NEWLINE=false \
  POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' ' \
  POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=238 \
  POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' ' \
  POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' ' \
  POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}' \
  POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}' \
  POWERLEVEL9K_MODE=powerline \
  POWERLEVEL9K_ICON_BEFORE_CONTENT=true \
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='%B%F{2}$%f%b' \
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='%B%F{1}$%f%b' \
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='%B%F{5}$%f%b' \
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='%B%F{3}$%f%b' \
  POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true \
  POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='' \
  POWERLEVEL9K_DIR_FOREGROUND=15 \
  POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=7 \
  POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right \
  POWERLEVEL9K_SHORTEN_DELIMITER= \
  POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=12 \
  POWERLEVEL9K_DIR_ANCHOR_BOLD=true \
  POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})" \
  POWERLEVEL9K_SHORTEN_DIR_LENGTH=1 \
  POWERLEVEL9K_DIR_MAX_LENGTH=1 \
  POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40 \
  POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50 \
  POWERLEVEL9K_DIR_HYPERLINK=false \
  POWERLEVEL9K_DIR_SHOW_WRITABLE=false \
  POWERLEVEL9K_DIR_CLASSES=() \
  POWERLEVEL9K_VCS_PREFIX='' \
  POWERLEVEL9K_VCS_BRANCH_ICON='%b %B' \
  POWERLEVEL9K_VCS_UNTRACKED_ICON='+' \
  POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true \
  POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter(1)))+${my_git_format}}' \
  POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${$((my_git_formatter(0)))+${my_git_format}}' \
  POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1 \
  POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=13 \
  POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=7 \
  POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION= \
  POWERLEVEL9K_VCS_BACKENDS=(git) \
  POWERLEVEL9K_VCS_CLEAN_FOREGROUND=13 \
  POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=3 \
  POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=6 \
  POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true \
  POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=14 \
  POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='=' \
  POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION= \
  POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%11F%n@%m%f%b:' \
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3 \
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0 \
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=7 \
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='' \
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s' \
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION= \
  POWERLEVEL9K_STATUS_EXTENDED_STATES=true \
  POWERLEVEL9K_STATUS_OK_PIPE=true \
  POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=10 \
  POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='↵' \
  POWERLEVEL9K_STATUS_ERROR=true \
  POWERLEVEL9K_STATUS_ERROR_FOREGROUND=9 \
  POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='↵' \
  POWERLEVEL9K_STATUS_ERROR_SIGNAL=true \
  POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=208 \
  POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false \
  POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='↵' \
  POWERLEVEL9K_STATUS_ERROR_PIPE=true \
  POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=9 \
  POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='↵'
  local anchor_files=(.git)
  POWERLEVEL9K_VCS_BRANCH_ICON=${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}
  POWERLEVEL9K_VCS_UNTRACKED_ICON=${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON}
  function my_git_formatter() {
    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi
    if (( $1 )); then
      local       meta='%13F'  # default foreground
      local      clean='%13F'  # green foreground
      local   modified='%13F'  # yellow foreground
      local  untracked='%13F'  # blue foreground
      local conflicted='%13F'  # red foreground
    else
      local       meta='%8F'  # grey foreground
      local      clean='%8F'  # grey foreground
      local   modified='%8F'  # grey foreground
      local  untracked='%8F'  # grey foreground
      local conflicted='%8F'  # grey foreground
    fi
    local res
    local where  # branch name, tag or commit
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      res+="${clean}${POWERLEVEL9K_VCS_BRANCH_ICON}"
      where=${(V)VCS_STATUS_LOCAL_BRANCH}
    elif [[ -n $VCS_STATUS_TAG ]]; then
      res+="${meta}#"
      where=${(V)VCS_STATUS_TAG}
    else
      res+="${meta}@"
      where=${VCS_STATUS_COMMIT[1,8]}
    fi
    (( $#where > 32 )) && where[13,-13]="…"
    res+="${clean}${where//\%/%%}"  # escape %
    if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
      res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"  # escape %
    fi
    (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}v${VCS_STATUS_COMMITS_BEHIND}"
    (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
    (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}^${VCS_STATUS_COMMITS_AHEAD}"
    (( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}"
    [[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}"
    (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}x${VCS_STATUS_NUM_CONFLICTED}"
    (( VCS_STATUS_NUM_STAGED     )) && res+=" ${modified}#${VCS_STATUS_NUM_STAGED}"
    (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}~${VCS_STATUS_NUM_UNSTAGED}"
    (( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}${POWERLEVEL9K_VCS_UNTRACKED_ICON}${VCS_STATUS_NUM_UNTRACKED}"
    typeset -g my_git_format=$res
  }
  functions -M my_git_formatter 2>/dev/null
}
