#!/bin/sh
chrootDir="$1"
mkdir -p "$chrootDir" 2>/dev/null
[ ! -e "$chrootDir" ] && echo "'${chrootDir}': no such directory." && exit 1
cd "${chrootDir}" || exit 1

mirror="http://dl-cdn.alpinelinux.org/alpine/"

shift
packages="$*"

printf 'Fetching static apk binary...\n'
wget -c -nv --show-progress -rnd -l1 --no-parent -A "apk-tools-static-*.apk" "${mirror}/edge/main/x86_64/"

printf '\nUnpacking static apk binary...\n'
tar --warning=none -xzf apk-tools-static-*.apk 1>/dev/null
rm -R apk-tools-static-*.apk sbin/apk.static.*

printf '\nInstalling the requested packages...\n'
sbin/apk.static -X ${mirror}/edge/main -X ${mirror}/edge/community -U --allow-untrusted --root "${chrootDir}" --initdb add ${packages}
[ -x sbin/apk ] && rm -R sbin/apk.static
