#!/bin/sh
export CHROME_WRAPPER="`readlink -f "$0"`"
export CHROME_USER_DATA_DIR="${XDG_CONFIG_HOME}/brave"

if [ -e "${XDG_CONFIG_HOME}/chromium-flags.conf" ]; then
  CHROMIUM_FLAGS="$(grep -Ev -- '^#|^--incognito' "${XDG_CONFIG_HOME}/chromium-flags.conf")"
fi

exec < /dev/null
exec > >(exec cat)
exec 2> >(exec cat >&2)

exec /opt/brave.com/brave*/brave ${CHROMIUM_FLAGS} "$@"
