#!/bin/sh
until [ -z "$1" ]; do
  case "$1" in
    -s|--start)
    shift
    START="-ss $1"
    shift
    ;;
    -e|--end)
    shift
    END="-to $1"
    shift
    ;;
    -o|--output)
    shift
    OUTPUT="$1"
    shift
    ;;
    -c|--copy)
    COPY="-c copy"
    shift
    ;;
    -k|--keep)
    KEEP=1
    shift
    ;;
    *)
    SOURCE="$1"
    shift
    ;;
  esac
done

mkdir -p "${XDG_CACHE_HOME}/cutclip"
[ -z "$OUTPUT" ] && OUTPUT="${XDG_CACHE_HOME}/cutclip/output.mp4"
[ -z "$SOURCE" ] && printf 'No file/URL specified.' && exit 1

case "$SOURCE" in http*://*|www.*|youtube.com/*|youtu.be/*)
  [ -z "$KEEP" ] && rm -R "${XDG_CACHE_HOME}/cutclip/source"* 2>/dev/null
  youtube-dl "$SOURCE" -o "${XDG_CACHE_HOME}/cutclip/source" || exit 1
  SOURCE="${XDG_CACHE_HOME}/cutclip/source"
  ;;
esac

ffmpeg -y ${START} ${END} -i "$SOURCE"* ${COPY} -map 0:v:0 -map 0:a:0 "$OUTPUT"

[ -z "$KEEP" ] && rm "${XDG_CACHE_HOME}/cutclip/source."* 2>/dev/null
