#!/bin/sh
if [ -e "${XDG_CACHE_HOME}/wal/colors.sh" ]; then
  . "${XDG_CACHE_HOME}/wal/colors.sh"
  exec /usr/bin/dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -i -l 20 -fn "Ubuntu Regular-12" $@
else
  exec /usr/bin/dmenu $@
fi
