#!/bin/dash
if [ ! -e "${XDG_CONFIG_HOME}/emacs/bin/doom" ]; then
  git clone --depth 1 https://github.com/hlissner/doom-emacs "${XDG_CONFIG_HOME}/emacs" && \
  "${XDG_CONFIG_HOME}/emacs/bin/doom" install
fi

exec "${XDG_CONFIG_HOME}/emacs/bin/doom" "$@"
