#!/bin/sh
TARGET="$1"
[ -z "$TARGET" ] && TARGET='.'

if echo "$0" | grep -q -- '/f$'; then
  TYPE='file' 
elif echo "$0" | grep -q -- '/d$'; then
  TYPE='directory'
fi

fd -LHp --threads "$(nproc)" --type "$TYPE" -E '/sys/' -E '/proc' . "$TARGET" | sort -d | $FUZZYFINDER
