#!/bin/dash
BASE="$(printf "%s" "$*" | sha512sum | cut -f 1 -d ' ' | base64 | tr -d '\n' | cut -c $(seq -s , 3 3 60))"
ONE="$(printf "%s" "$BASE" | cut -c 1-5)"
TWO="$(printf "%s" "$BASE" | cut -c 6-10)"
THREE="$(printf "%s" "$BASE" | cut -c 11-15)"
FOUR="$(printf "%s" "$BASE" | cut -c 16-20)"

echo "$ONE!$TWO+$THREE\$$FOUR"
