#!/bin/dash
[ -e "${HOME}/.cache/wal/colors.sh" ] && . "${HOME}/.cache/wal/colors.sh"

FONT="$(grep gtk-font-name "${XDG_CONFIG_HOME}/gtk-3.0/settings.ini" | rev | cut -f 2- -d ' ' | rev | cut -f 2- -d '=')"
SIZE="$(grep gtk-font-name "${XDG_CONFIG_HOME}/gtk-3.0/settings.ini" | rev | cut -f 1 -d ' ' | rev)"

exec /usr/bin/lemonbar -o -2 -B "$background" -F "$color7" -f "Font Awesome:size=13:antialias=true" -f "${FONT}:style=Regular:size=${SIZE}:antialias=true" $@
