#!/bin/dash
. "${XDG_CACHE_HOME}/wal/colors.sh"

exec /usr/bin/mako --font 'Ubuntu Regular 14' \
  --max-history=20 --default-timeout=10000 \
  --anchor=bottom-right --width=400 --height=150 --margin=0,20,35 --padding=0,8,10 --border-size=2 \
  --background-color "$background" --text-color "$foreground" --border-color="$color5" --progress-color="$color5" \
  "$@"
