#!/bin/sh
echo "$0"
if [ -n "$1" ]; then
  INPUT="$1"
else
  INPUT='-'
fi

CONTENT="$(cat $INPUT)"
LINES="$(printf '%s' "$CONTENT" | wc -l)"

if [ "$LINES" -eq '0' ]; then
  true
else
  case "$0" in
    *nvimanpager)
      echo "$CONTENT" | exec nvim -c 'set nobuflisted buftype=nofile bufhidden=wipe noswapfile modifiable filetype=man' -c 'nnoremap q :q!<CR>' ;;
    *)
      echo "$CONTENT" | exec nvim -c 'set nobuflisted buftype=nofile bufhidden=wipe noswapfile modifiable' -c 'filetype detect' -c 'nnoremap q :q!<CR>' "+ normal G $" ;;
  esac
fi
