#!/bin/dash
# COUNTRY='country=CZ&country=SK&country=PL&country=AT&country=DE'
COUNTRY='country=CZ&country=SK&country=PL&country=AT'
curl -s "https://archlinux.org/mirrorlist/?${COUNTRY}&protocol=https&ip_version=4&use_mirror_status=on" \
  | sed -e '/^##/d;/^$/d;s/^#//g' \
  | rankmirrors -n 0 - > /etc/pacman.d/mirrorlist
