#!/bin/dash
if [ "$TERM" = 'linux' ]; then
  MENU="rofi -dmenu -p "$1""
else
  MENU="$FUZZYFINDER --prompt "$1""
fi

if type wl-copy >/dev/null 2>&1; then
  CLIPBOARD='wl-copy'
elif type termux-clipboard-set >/dev/null 2>&1; then
  CLIPBOARD='termux-clipboard-set'
else
  CLIPBOARD='xclip'
fi

pass >/dev/null

case "$1" in
  pass*)
    pass -c "$(fd '.gpg$' "$PASSWORD_STORE_DIR" | awk -F "${PASSWORD_STORE_DIR}/|.gpg" '{print $2}' | $MENU)" > /dev/null ;;
  user*|name*)
    fd '.gpg$' "$PASSWORD_STORE_DIR" | awk -F "${PASSWORD_STORE_DIR}/|.gpg" '{print $2}' | $MENU | rev | cut -f 1 -d '/' | rev | $CLIPBOARD ;;
esac
