#!/bin/dash
MENU="rofi -dmenu -p "$1""

case "$1" in
  *name*)
    LINE=1 ;;
  *pass*)
    LINE=2 ;;
esac

if type wl-copy >/dev/null 2>&1; then
  CLIPBOARD='wl-copy'
elif type termux-clipboard-set >/dev/null 2>&1; then
  CLIPBOARD='termux-clipboard-set'
else
  CLIPBOARD='xclip'
fi

pass ls "$(fd '.gpg$' "$PASSWORD_STORE_DIR" | awk -F "${PASSWORD_STORE_DIR}/|.gpg" '{print $2}' | $MENU --prompt password)" | sed -n "${LINE}p" | "$CLIPBOARD"
