#!/bin/dash
[ -z "$PASSWORD_STORE_DIR" ] && PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"
GNUPGHOME="${PASSWORD_STORE_DIR}/.gpg"

if [ ! -e "${GNUPGHOME}/pubring.kbx" ]; then
  mkdir -p "$GNUPGHOME"
  chmod 700 "$GNUPGHOME"
  gpg --no-tty --quick-gen-key --yes pass
  pass init pass
  exit 0
fi

exec /usr/bin/pass "$@"
