#!/bin/sh
 color0="${1}"
 color1="${2}"
 color2="${3}"
 color3="${4}"
 color4="${5}"
 color5="${6}"
 color6="${7}"
 color7="${8}"
 color8="${09:-"$color0"}"
 color9="${10:-"$color1"}"
color10="${11:-"$color2"}"
color11="${12:-"$color3"}"
color12="${13:-"$color4"}"
color13="${14:-"$color5"}"
color14="${15:-"$color6"}"
color15="${16:-"$color7"}"

cat <<EOF
{
  "special": {
    "background": "$color0",
    "foreground": "$color7",
    "cursor":     "$color5"
  },
  "colors": {
    "color0":     "$color0",
    "color1":     "$color1",
    "color2":     "$color2",
    "color3":     "$color3",
    "color4":     "$color4",
    "color5":     "$color5",
    "color6":     "$color6",
    "color7":     "$color7",
    "color8":     "$color8",
    "color9":     "$color9",
    "color10":    "$color10",
    "color11":    "$color11",
    "color12":    "$color12",
    "color13":    "$color13",
    "color14":    "$color14",
    "color15":    "$color15"
    }
}
EOF
