#!/bin/bash
export CHROME_WRAPPER="`readlink -f "$0"`"
[ -z "$CHROME_USER_DATA_DIR" ] && export CHROME_USER_DATA_DIR="${XDG_CONFIG_HOME}/chromium"

if [ -e "${XDG_CONFIG_HOME}/chromium-flags.conf" ]; then
  CHROMIUM_FLAGS="$(awk '!/^#/ {print $1}' "${XDG_CONFIG_HOME}/chromium-flags.conf")"
fi

for BIN in /usr/bin/chromium /opt/appimages/ungoogled-chromium-*.AppImage; do
  [ -x "$BIN" ] && CHROMIUM="$BIN" && break
done
[ -z "$CHROMIUM" ] && printf 'No suitable Chromium binary found.\n' && exit 1

_sanitize() {
  if ! pidof chromium >/dev/null; then
    rm $(fd --type=file -HL . "$CHROME_USER_DATA_DIR" | grep -Ev 'Extension|Preferences|Bookmarks|Dictionaries|WidevineCdm|NativeMessagingHosts' | tr ' ' '*') 2>/dev/null
    rm -R "${XDG_CACHE_HOME}/chromium" 2>/dev/null
  fi
}

exec < /dev/null
exec > >(exec cat)
exec 2> >(exec cat >&2)

_sanitize
"$CHROMIUM" ${CHROMIUM_FLAGS} "$@"
_sanitize
